# INSERT

- INSERT문은 테이블에 데이터를 입력하는 DML문 
- 데이터를 입력할 때 문자열을 입력하는 경우 작은 따옴표(' ')를 사용함
- 특정 테이블의 모든 칼럼에 대한 데이터를 삽입하는 경우 컬럼명 생략 가능 
- INSERT 문을 실행했다고 데이터 파일에 저장되는 것은 아니기 때문에 TCL문인 Commit을 실행해야 함. 
- Auto Commit으로 설정된 경우 Commit할 필요는 없음. 

## 기본 문법 

```SQL
INSERT INTO [table] ([column1], [column2], ... )
VALUES ([expression1], [expression2], ... );
```

## SELECT 문을 사용하는 방법 

```SQL
INSERT INTO [table1]
SELECT * FROM [table2];
```

## Nologging을 사용하는 방법

- 데이터베이스에 데이터를 입력하면 로그파일에 그 정보를 기록함
- Check point라는 이벤트가 발생하면 로그파일의 데이터를 데이터 파일에 저장
- Nologging 옵션은 로그파일의 기록을 최소화시켜 입력 시 성능을 향상시킴

```SQL
ALTER TABLE [table] NOLOGGING;
```

# UPDATE

- 입력된 데이터의 값을 수정함
- 원하는 조건으로 데이터를 검색해서 해당 데이터를 수정할 수 있음 
- 조건문을 입력하지 않으면 모든 데이터가 수정되므로 유의해야 함 

## 기본 문법 

```SQL
UPDATE [table]
 SET [column1] = [expression1],
     [column2] = [expression2]
WHERE [column1] = [expression1];
```

# DELETE

- 원하는 조건을 검색해서 해당되는 행을 삭제 
- 조건문을 입력하지 않으면 모든 데이터가 삭제되므로 유의해야 함 
- 실행시 테이블 용량은 초기화되지 않음 

## 기본 문법 

```SQL
DELETE FROM [table] 
WHERE [expression]; 
```

## DELETE vs TRUNCATE

**1. DELETE**
- 테이블의 모든 데이터를 삭제함 
- 데이터가 삭제되어도 테이블의 용량은 감소하지 않음 

**2. TRUNCATE**
- 테이블의 모든 데이터를 삭제함 
- 데이터가 삭제되면 테이블의 용량은 초기화됨

# SELECT

- 테이블에 입력된 데이터를 조회하기 위해 사용 
- 특정 칼럼이나 특정 행만을 조회함 

## 기본 문법 

```SQL
SELECT *
  FROM [table] 
WHERE [expression];
```

- SELECT 문 뒤에 입력되는 칼럼은 모두 출력함
- 모든 칼럼을 출력할 경우 * 를 사용함

## Sorting 

**1. ORDER BY를 사용한 정렬**

- SELECT 문을 사용할 때 ORDER BY를 사용할 수 있음
- ORDER BY는 데이터를 오름차순 혹은 내림차순으로 정렬함
- ORDER BY는 모든 실행이 끝난 후 데이터를 출력하기 전에 실행됨 
- Default 옵션은 오름차순이고 DESC 옵션을 추가하면 내림차순으로 정렬함 

```SQL
SELECT FROM [table] 
 ORDER BY [column1], [column2] DESC; 
```

**2. INDEX를 사용한 정렬회피**

- 정렬은 데이터베이스에 부하를 주기 떄문에 인덱스를 사용해서 ORDER BY를 회피할 수 있음
- 기본키의 경우 테이블의 인덱스로 자동 지정됨
- 따라서 인덱스로 데이터를 정렬한 효과를 줄 수 있음

```SQL
SELECT /*+ INDEX_DESC([table]) */ *
 FROM [table]
```

## DISTINCT

- DISTINCT문은 컬럼명 앞에 지정하여 중복된 데이터를 한 번만 조회함

```SQL
SELECT DISTINT [column1]
  FROM [table];
```

## ALIAS 

- Alias(별칭)은 테이블명이나 칼럼명이 너무 길어서 축약할 때 사용

```SQL
SELECT [column1] AS [col1]
 FROM [table] AS [tb1]
WHERE [tb1].[col1]
```

# WHERE 문 사용

## 비교 연산자 

- = : 같은 것을 조회  
- < : 작은 것을 조회
- <= : 작거나 같은 것을 조회
- > : 큰 것을 조회
- >= : 크거나 같은 것을 조회 

## 부정 비교 연산자 

- != : 같지 않은 것을 조회
- ^= : 같지 않은 것을 조회
- <> : 같지 않은 것을 조회
- NOT [column] = : 같지 않은 것을 조회
- NOT [column] > : 크지 않은 것을 조회

## 논리 연산자 

- AND : 조건을 모두 만족해야 참
- OR : 조건 중 하나만 만족해도 참
- NOT : 참이면 거짓으로, 거짓이면 참으로 변경

## SQL 연산자 

- LIKE '%[expression]%' : [expression]을 조회
- BETWEEN A AND B : A와 B사이의 값을 조회
- IN(list) : lsit 값중에 하나만 일치해도 조회
- IS NULL : NULL 값을 조회

## LIKE의 사용 

- LIKE문은 와일드카드를 사용해서 데이터를 조회할 수 있음
- % : 어떤 문자를 표함한 모든 것을 조회함 (%S%)는 중간에 S만 존재하면 됨 
- _ : 한 개의 단일 문자만을 포함 

## NULL 함수 

**1. NVL**
- NULL 이면 다른 값으로 바꾼다. 
- NULL(MGR, 0) : MGR 컬럼이 NULL이면 0으로 변경 

**2. NVL2**
- NVL + DECODE의 역할을 수행함 
- NVL2(MGR, 1, 0) : MGR 컬럼이 NULL이 아니면 1을, NULL이면 0으로 변경 

**3. NULLIF**
- 두개의 값이 같으면 NULL을, 같지 않으면 첫번째 값을 반환 

**4. COALESCE**
- NULL이 아닌 최초의 인자값을 반환
- COALESCE(exp1, exp2, ...) : exp1이 NULL이 아니면 exp1을, 그렇지 않으면 그 뒤의 값의 NULL 여부를 판단하여 값을 변환함

## GROUP BY

**1. 함수의 기능**
- 테이블에서 소규모 행을 그룹화하여 합계, 평균, 최댓값, 최솟값 등을 계산 가능 

**2. 기본 문법**

```SQL
SELECT AGG_FUNC([column])
  FROM [table]
 GROUP BY [column];
```

## HAVING
- GROUP BY 문에서 조건을 제시할 경우 HAVING을 사용해야 함 
- WHERE를 사용하면 GROUP BY를 적용하기 전에 GROUP BY 대상에서 제외됨 

```SQL
SELECT AGG_FUNC([column])
  FROM [table]
 GROUP BY [column]
HAVING AGG_FUNC([column]) > [expressions];
```

## Aggregate function

- COUNT() : 행 수를 조회 
- SUM() : 합계를 계산 
- AVG(): 평균을 계산 
- MAX(), MIN() : 최댓값과 최솟값을 계산 
- STDEV() : 표준편차를 계산 
- VARIAN() : 분산을 계산함 

**About COUNT**
- COUNT() 함수는 행 수를 계산하는 함수 
- COUNT(*) : NULL값을 포함한 모든 행 수를 계산함

## SELECT문 실행 순서 

FROM - WHERE - GROUP BY - HAVING - SELECT - ORDER BY

# 명시적/암시적 형변환 

- 형변환은 두 개의 데이터의 데이터 타입이 일치하도록 변환하는 것
- 명시적 형변환 : 형변환 함수를 사용해서 데이터 타입을 일치시키는 것
- 암시적 형변환 : 개발자가 형변환을 하지 않은 경우 데이터베이스 관리 시스템이 자동으로 형변환하는 것
- 인덱스 칼럼에 형변환을 수행하면 인덱스를 사용하지 못함

## 명시적 형변환 함수 

- TO_NUMERIC([char]) : 문자열을 숫자형으로 변환 
- TO_CHAR([int/date], [format]) : 숫자 혹은 날짜를 지정된 format의 문자로 변환
- TO_DATE([char], [format]) : 문자열로 지정된 format의 날짜형으로 변환

## 명시적 커서 

1. 커서 선언(CURSOR DEFINE) : 사용할 커서에 이름을 부여하고 이 커서에 대한 쿼리를 선언한다.
2. 커서 열기(OPEN CURSOR) : 사용할 커서를 오픈한다.
3. 패치 단계에서 커서 사용(FETCH) : 결과 집합의 행수는 보통 1개 이상이므로 각각의 개별 행에 접근하기 위해 반복문 사용
4. 커서 닫기(CLOSE CURSOR) : 커서 사용이 끝났으면 닫아준다.

# 내장형 함수(Built-In Function) 

- 모든 데이터베이스는 SQL에서 사용할 수 있는 내장형 함수가 존재
- 형변환 함수, 문자열 및 숫자형 함수, 날짜형 함수가 있음

## DUAL 테이블 

- Oracle 데이터베이스에 의해서 자동으로 생성되는 테이블
- 사용자가 임시로 사용할 수 있는 더미 테이블

## 내장형 함수 종류 

**1. 문자열 함수**
- ASCII([char]) : 문자 혹은 숫자를 ASCII 코드값으로 변환
- CHAR([ascii]) : ASCII 코드 값을 문자로 변환
- SUBSTR([char],m,n) : 문자열에서 m번째 위치부터 n개를 자름
- CONCAT([char1], [char2]) : 문자열 1번과 문자열 2번을 결합
- LOWER([char]) : 영문자를 소문자로 변환
- UPPER([char]) : 영문자를 대문자로 변환
- LENGTH([char]) : 문자열의 길이
- LTRIM([char], [expression]) : 왼쪽에서 지정된 문자를 삭제
- RTRIM([char], [expression]) : 오른쪽에서 지정된 문자를 삭제
- TRIM([char], [expression]) : 왼쪽 및 오른쪽에서 지정된 문자를 삭제

**2. 날짜형 함수**
- SYNDATE : 오늘 날짜
- EXTRACT('YEAR'|'MONTH' FROM [table]) : 날짜에서 년,월을 조회

**3. 숫자형 함수**
- ABS([int]) : 절댓값을 돌려줌
- SIGN([int]) : 양수, 음수, 0을 구분함
- MOD([int1], [int2]) : 숫자1을 숫자2로 나누어 나머지를 계산
- CEIL/CEILING([int]) : 숫자보다 크거나 같은 최소의 정수를 돌려줌
- FLOOR([int]) : 숫자보다 작거나 같은 최대의 정수를 돌려줌
- ROUND([int], n) : 소수점 n자리에서 반올림 함
- TRUNC([int], n) : 소수점 n자리에서 절삭함

# DECODE

- DECODE 문으로 IF 문을 구현 가능하며, 특정 조건이 참이면 A, 거짓이면 B를 반환한다

```SQL
SELECT DECODE([column], n, 'TRUE', 'FALSE')
  FROM [table];
```

# CASE

- CASE문은 IF ~ THEN ~ ELSE - END의 프로그래밍 언어처럼 조건문을 사용할 수 있음
- 조건을 WHEN 구에 사용하고 THEN은 해당 조건이 참이면 실행되고 거짓이면 ELSE구가 실행된다

```SQL
SELECT
 CASE
 WHEN [condition_1] THEN [result_1]
 WHEN [condition_2] THEN [result_2]
 ...
 WHEN [condition_n] THEN [result_n]
 ELSE [result]
 END AS [new_col]
 FROM [table];
```

# ROWNUM

- ROWNUM은 ORACLE 데이터베이스의 SELECT문 결과에 대해서 논리적인 일련번호를 부여함
- ROWNUM은 조회되는 행 수를 제한할 때 사용
- SQLite의 LIMIT n;과 표현이 동일함
- 인라인 뷰(Inline view)는 SELECT 문에서 FROM 절에 사용되는 서브 쿼리를 의미하며 ROW NUM에 별칭을 사용해서 출력 수를 정해야 함

## n 번째 행까지 조회

```SQL
SELECT * FROM [table]
WHERE ROWNUM < n;
```

## n 번째 인라인 뷰의 행 조회 

```SQL
SELECT *
  FROM (SELECT ROWNUM AS list, [column] FROM [table])
 WHERE list < n;
```

## m ~ n 번째 인라인 뷰의 행 조회 

```SQL
SELECT *
  FROM (SELECT ROWNUM AS list, [column] FROM [table])
 WHERE list BETWEEN m AND n;
```

# ROWID

- ROWID는 ORACLE 데이터베이스 내에서 데이터를 구분할 수 있는 유일한 값임
- ROWID를 통해서 데이터가 어떤 데이터 파일, 어느 블록에 저장되어 있는지 확인 가능
- ROWID 구조
    - 오브젝트 번호(1~6) : 해당 오브젝트가 속해 있는 값
    - 상대 파일 번호(7~9) : 데이터 파일에 대한 상대 파일 번호
    - 블록 번호(10~15) : 데이터 파일 내부에서 어느 블록에 데이터가 있는지 알려줌
    - 데이터 번호(16~18) : 데이터 블록에 데이터가 저장되어 있는 순서
    
```SQL
SELECT ROWID FROM [table];
```

# WITH Clause 

- WITH구문은 서브쿼리를 사용해서 임시 테이블이나 뷰처럼 사용할 수 있는 구문
- 옵티마이저는 SQL을 인라인 뷰나 임시 테이블로 판단함

```SQL
WITH [view_name] AS (
 SELECT * FROM [table]
 ...
 )
 SELECT * FROM [view_name] ...;
```