In [1]:
import pandas as pd
x_train = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/studentscore/X_train.csv")
y_train = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/studentscore/y_train.csv")
x_test= pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/studentscore/X_test.csv")

# Check dataset
print(x_train.head(3))
print(x_test.head(3))
print(y_train.head(3))
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)

# Missing values
print(x_train.info())
print(x_test.info())

# Copy dataset and set 'ID' as index
train = x_train.copy().set_index('StudentID')
test = x_test.copy().set_index('StudentID')
y = y_train.copy().set_index('StudentID')

# Check object variables
obj_cols = train.select_dtypes(include = ['object']).columns
for col in obj_cols :
    print(train[col].value_counts().head())
    print(train[col].unique())
    print(train[col].nunique())
    print(test[col].value_counts().head())
    print(test[col].unique())
    print(test[col].nunique())

# Drop column 'G1'
train = train.drop(columns = 'G1')
test = test.drop(columns = 'G1')

# Check numerical variables
print(train.describe())
print(train.corr())

# Process outliers
num_cols = train.select_dtypes(exclude = ['object']).columns
cnt_cols = [col for col in num_cols if train[col].nunique() < 10]
dct_cols = [col for col in num_cols if col not in cnt_cols]
for col in cnt_cols :
    Q1 = train[col].quantile(0.25)
    Q3 = train[col].quantile(0.75)
    IQR = Q3 - Q1
    upper = Q3 + 1.5 * IQR
    lower = Q1 - 1.5 * IQR
    train.loc[train[col] > upper, col] = upper
    train.loc[train[col] < lower, col] = lower
    test.loc[test[col] > upper, col] = upper
    test.loc[test[col] < lower, col] = lower

# Preprocessing
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
X = train[num_cols]
X_test = test[num_cols]
X[num_cols] = mm.fit_transform(X[num_cols])
X_test[num_cols] = mm.transform(X_test[num_cols])
X_obj = pd.get_dummies(train[obj_cols])
X_test_obj = pd.get_dummies(test[obj_cols])
X = pd.concat([X, X_obj], axis = 1)
X_test = pd.concat([X_test, X_test_obj], axis = 1)
print(X.shape, X_test.shape)

# Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size = 0.2)

# Modeling
from sklearn.model_selection import GridSearchCV
from xgboost import XGBRegressor
# xgb = XGBRegressor(random_state = 42)
# params = {'max_depth' : [6, 8], 'n_estimators' : [200, 300], 'min_child_weight' : [4, 5]}
# grid = GridSearchCV(xgb, param_grid = params, cv = 4)
# grid.fit(X_train, y_train)
# print(grid.best_estimator_)

# Model Evaluation
from sklearn.metrics import r2_score
import numpy as np
best_xgb = XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
                        colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
                        gamma=0, gpu_id=-1, importance_type=None,
                        interaction_constraints='', learning_rate=0.300000012,
                        max_delta_step=0, max_depth=6, min_child_weight=4, missing=np.nan,
                        monotone_constraints='()', n_estimators=200, n_jobs=12,
                        num_parallel_tree=1, predictor='auto', random_state=42,
                        reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
                        tree_method='exact', validate_parameters=1, verbosity=None)
best_xgb.fit(X_train, y_train)
preds = best_xgb.predict(X_valid)
print(r2_score(y_valid, preds))

# Make submission
pred = best_xgb.predict(X_test)
pd.DataFrame({'StudentID' : X_test.index, 'G3' : pred}).to_csv('0001.csv', index = False)
df = pd.read_csv('0001.csv')
print(df.head())

   StudentID school sex  age address famsize Pstatus  Medu  Fedu    Mjob  ...  \
0       1714     GP   F   18       U     GT3       T     4     3   other  ...
1       1254     GP   F   17       U     GT3       T     4     3  health  ...
2       1639     GP   F   16       R     GT3       T     4     4  health  ...

  romantic famrel freetime  goout  Dalc  Walc health absences  G1  G2
0       no      4        3      3     1     1      3        0  14  13
1      yes      4        4      3     1     3      4        0  13  15
2       no      2        4      4     2     3      4        6  10  11

[3 rows x 33 columns]
   StudentID school sex  age address famsize Pstatus  Medu  Fedu      Mjob  \
0       1000     GP   F   16       U     GT3       T     4     2  services
1       1008     GP   M   19       U     GT3       T     1     2     other
2       1013     GP   F   16       U     GT3       T     4     4  services

   ... romantic famrel freetime  goout  Dalc  Walc health absences  G1  G2
0  ...       no      4        2      3     1     1      5        2  15  16
1  ...       no      4        5      2     2     2      4        3  13  11
2  ...       no      3        2      3     1     2      2        6  13  14

[3 rows x 33 columns]
   StudentID  G3
0       1714  14
1       1254  15
2       1639  11
(678, 33)
(366, 33)
(678, 2)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 678 entries, 0 to 677
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   678 non-null    int64
 1   school      678 non-null    object
 2   sex         678 non-null    object
 3   age         678 non-null    int64
 4   address     678 non-null    object
 5   famsize     678 non-null    object
 6   Pstatus     678 non-null    object
 7   Medu        678 non-null    int64
 8   Fedu        678 non-null    int64
 9   Mjob        678 non-null    object
 10  Fjob        678 non-null    object
 11  reason      678 non-null    object
 12  guardian    678 non-null    object
 13  traveltime  678 non-null    int64
 14  studytime   678 non-null    int64
 15  failures    678 non-null    int64
 16  schoolsup   678 non-null    object
 17  famsup      678 non-null    object
 18  paid        678 non-null    object
 19  activities  678 non-null    object
 20  nursery     678 non-null    object
 21  higher      678 non-null    object
 22  internet    678 non-null    object
 23  romantic    678 non-null    object
 24  famrel      678 non-null    int64
 25  freetime    678 non-null    int64
 26  goout       678 non-null    int64
 27  Dalc        678 non-null    int64
 28  Walc        678 non-null    int64
 29  health      678 non-null    int64
 30  absences    678 non-null    int64
 31  G1          678 non-null    int64
 32  G2          678 non-null    int64
dtypes: int64(16), object(17)
memory usage: 174.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   366 non-null    int64
 1   school      366 non-null    object
 2   sex         366 non-null    object
 3   age         366 non-null    int64
 4   address     366 non-null    object
 5   famsize     366 non-null    object
 6   Pstatus     366 non-null    object
 7   Medu        366 non-null    int64
 8   Fedu        366 non-null    int64
 9   Mjob        366 non-null    object
 10  Fjob        366 non-null    object
 11  reason      366 non-null    object
 12  guardian    366 non-null    object
 13  traveltime  366 non-null    int64
 14  studytime   366 non-null    int64
 15  failures    366 non-null    int64
 16  schoolsup   366 non-null    object
 17  famsup      366 non-null    object
 18  paid        366 non-null    object
 19  activities  366 non-null    object
 20  nursery     366 non-null    object
 21  higher      366 non-null    object
 22  internet    366 non-null    object
 23  romantic    366 non-null    object
 24  famrel      366 non-null    int64
 25  freetime    366 non-null    int64
 26  goout       366 non-null    int64
 27  Dalc        366 non-null    int64
 28  Walc        366 non-null    int64
 29  health      366 non-null    int64
 30  absences    366 non-null    int64
 31  G1          366 non-null    int64
 32  G2          366 non-null    int64
dtypes: int64(16), object(17)
memory usage: 94.5+ KB
None
GP    509
MS    169
Name: school, dtype: int64
['GP' 'MS']
2
GP    263
MS    103
Name: school, dtype: int64
['GP' 'MS']
2
F    394
M    284
Name: sex, dtype: int64
['F' 'M']
2
F    197
M    169
Name: sex, dtype: int64
['F' 'M']
2
U    499
R    179
Name: address, dtype: int64
['U' 'R']
2
U    260
R    106
Name: address, dtype: int64
['U' 'R']
2
GT3    479
LE3    199
Name: famsize, dtype: int64
['GT3' 'LE3']
2
GT3    259
LE3    107
Name: famsize, dtype: int64
['GT3' 'LE3']
2
T    602
A     76
Name: Pstatus, dtype: int64
['T' 'A']
2
T    321
A     45
Name: Pstatus, dtype: int64
['T' 'A']
2
other       254
services    165
at_home     118
teacher      89
health       52
Name: Mjob, dtype: int64
['other' 'health' 'services' 'at_home' 'teacher']
5
other       145
at_home      76
services     74
teacher      41
health       30
Name: Mjob, dtype: int64
['services' 'other' 'teacher' 'at_home' 'health']
5
other       371
services    196
teacher      43
at_home      42
health       26
Name: Fjob, dtype: int64
['other' 'teacher' 'services' 'at_home' 'health']
5
other       213
services     96
teacher      22
at_home      20
health       15
Name: Fjob, dtype: int64
['other' 'services' 'at_home' 'teacher' 'health']
5
course        269
reputation    172
home          165
other          72
Name: reason, dtype: int64
['reputation' 'other' 'course' 'home']
4
course        161
home           93
reputation     76
other          36
Name: reason, dtype: int64
['course' 'reputation' 'home' 'other']
4
mother    475
father    153
other      50
Name: guardian, dtype: int64
['father' 'mother' 'other']
3
mother    253
father     90
other      23
Name: guardian, dtype: int64
['mother' 'other' 'father']
3
no     604
yes     74
Name: schoolsup, dtype: int64
['no' 'yes']
2
no     321
yes     45
Name: schoolsup, dtype: int64
['no' 'yes']
2
yes    419
no     259
Name: famsup, dtype: int64
['yes' 'no']
2
yes    221
no     145
Name: famsup, dtype: int64
['yes' 'no']
2
no     537
yes    141
Name: paid, dtype: int64
['yes' 'no']
2
no     287
yes     79
Name: paid, dtype: int64
['no' 'yes']
2
no     350
yes    328
Name: activities, dtype: int64
['no' 'yes']
2
yes    188
no     178
Name: activities, dtype: int64
['no' 'yes']
2
yes    543
no     135
Name: nursery, dtype: int64
['yes' 'no']
2
yes    292
no      74
Name: nursery, dtype: int64
['yes' 'no']
2
yes    621
no      57
Name: higher, dtype: int64
['yes' 'no']
2
yes    334
no      32
Name: higher, dtype: int64
['yes' 'no']
2
yes    541
no     137
Name: internet, dtype: int64
['yes' 'no']
2
yes    286
no      80
Name: internet, dtype: int64
['yes' 'no']
2
no     433
yes    245
Name: romantic, dtype: int64
['no' 'yes']
2
no     240
yes    126
Name: romantic, dtype: int64
['no' 'yes']
2
              age        Medu        Fedu  traveltime   studytime    failures  \
count  678.000000  678.000000  678.000000   678.00000  678.000000  678.000000
mean    16.719764    2.607670    2.371681     1.50590    1.989676    0.261062
std      1.239881    1.134682    1.096750     0.73675    0.848082    0.664340
min     15.000000    0.000000    0.000000     1.00000    1.000000    0.000000
25%     16.000000    2.000000    1.000000     1.00000    1.000000    0.000000
50%     17.000000    3.000000    2.000000     1.00000    2.000000    0.000000
75%     18.000000    4.000000    3.000000     2.00000    2.000000    0.000000
max     22.000000    4.000000    4.000000     4.00000    4.000000    3.000000

           famrel    freetime       goout        Dalc        Walc      health  \
count  678.000000  678.000000  678.000000  678.000000  678.000000  678.000000
mean     3.933628    3.233038    3.140118    1.480826    2.293510    3.522124
std      0.952346    1.042083    1.165537    0.895789    1.287705    1.431430
min      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000
25%      4.000000    3.000000    2.000000    1.000000    1.000000    2.000000
50%      4.000000    3.000000    3.000000    1.000000    2.000000    4.000000
75%      5.000000    4.000000    4.000000    2.000000    3.000000    5.000000
max      5.000000    5.000000    5.000000    5.000000    5.000000    5.000000

         absences          G2
count  678.000000  678.000000
mean     4.594395   11.182891
std      6.527236    3.296146
min      0.000000    0.000000
25%      0.000000    9.000000
50%      2.000000   11.000000
75%      6.000000   13.000000
max     75.000000   19.000000
                 age      Medu      Fedu  traveltime  studytime  failures  \
age         1.000000 -0.132860 -0.140538    0.055174  -0.028041  0.259307
Medu       -0.132860  1.000000  0.637230   -0.246363   0.081743 -0.189205
Fedu       -0.140538  0.637230  1.000000   -0.198317   0.008896 -0.186079
traveltime  0.055174 -0.246363 -0.198317    1.000000  -0.093282  0.103983
studytime  -0.028041  0.081743  0.008896   -0.093282   1.000000 -0.157755
failures    0.259307 -0.189205 -0.186079    0.103983  -0.157755  1.000000
famrel      0.010495  0.030544  0.012340    0.001612   0.041214 -0.077633
freetime    0.032327 -0.028747 -0.059096   -0.009489  -0.124297  0.121088
goout       0.117159 -0.011983 -0.001513    0.032579  -0.071757  0.065239
Dalc        0.109528 -0.000146 -0.001756    0.107602  -0.170389  0.101502
Walc        0.085824 -0.005991  0.059653    0.036317  -0.223099  0.093323
health     -0.056425 -0.011018  0.070966   -0.042143  -0.039356  0.030420
absences    0.132313  0.079398  0.055754   -0.030064  -0.099487  0.078957
G2         -0.109604  0.253413  0.203855   -0.175014   0.177164 -0.369905

              famrel  freetime     goout      Dalc      Walc    health  \
age         0.010495  0.032327  0.117159  0.109528  0.085824 -0.056425
Medu        0.030544 -0.028747 -0.011983 -0.000146 -0.005991 -0.011018
Fedu        0.012340 -0.059096 -0.001513 -0.001756  0.059653  0.070966
traveltime  0.001612 -0.009489  0.032579  0.107602  0.036317 -0.042143
studytime   0.041214 -0.124297 -0.071757 -0.170389 -0.223099 -0.039356
failures   -0.077633  0.121088  0.065239  0.101502  0.093323  0.030420
famrel      1.000000  0.098958  0.057628 -0.128756 -0.114175  0.106724
freetime    0.098958  1.000000  0.297785  0.091823  0.096454  0.055953
goout       0.057628  0.297785  1.000000  0.238133  0.359336 -0.009386
Dalc       -0.128756  0.091823  0.238133  1.000000  0.647071  0.063113
Walc       -0.114175  0.096454  0.359336  0.647071  1.000000  0.093836
health      0.106724  0.055953 -0.009386  0.063113  0.093836  1.000000
absences   -0.050911 -0.036030  0.038353  0.131170  0.135092 -0.027416
G2          0.034459 -0.090693 -0.124717 -0.119374 -0.097580 -0.074742

            absences        G2
age         0.132313 -0.109604
Medu        0.079398  0.253413
Fedu        0.055754  0.203855
traveltime -0.030064 -0.175014
studytime  -0.099487  0.177164
failures    0.078957 -0.369905
famrel     -0.050911  0.034459
freetime   -0.036030 -0.090693
goout       0.038353 -0.124717
Dalc        0.131170 -0.119374
Walc        0.135092 -0.097580
health     -0.027416 -0.074742
absences    1.000000 -0.071038
G2         -0.071038  1.000000

(678, 57) (366, 57)

/tmp/ipykernel_11085/2587660087.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[num_cols] = mm.fit_transform(X[num_cols])
/tmp/ipykernel_11085/2587660087.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test[num_cols] = mm.transform(X_test[num_cols])

ModuleNotFoundError: No module named 'xgboost'